version: '3.9'

services:
  dash:
    # This is for that asking the container to execute the main.py
    command: python3 app_flask.py
    # The image I upload to my docker hub
    image: kyithinnu/a2carpriceprediction:3.2
    # For MAC M1 user
    platform: linux/x86_64
    # This will ask DASH to run on 0.0.0.0 and port 80
    environment:
      - HOST=0.0.0.0
      - PORT = 80
    # ports:
    #   - 8000:80
    # This is important for asking Traefik to use your container.
    # volumes:
    #   - ./source_code:/root/source_code
    #   - ./vscode-sever:/root/.vscode-server
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.web-st124087.loadbalancer.server.port=80
      # This config you domain name. By default, your subdomain is web-st124087
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.web-st124087.rule=Host(`st124087.ml2023.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.web-st124087.tls=true
      - traefik.http.routers.web-st124087.tls.certresolver=production
      - traefik.http.routers.web-st124087.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true